version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: nextjs-db
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nextjs
      MYSQL_USER: nextjsuser
      MYSQL_PASSWORD: abc1234
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
